--- #YAML:1.0
name:                HTML-Form-ForceValue
version:             0.006
abstract:            who cares what values are legal, anyway?
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    HTML::Form:                    0
    Sub::Exporter:                 0.960
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
